import React, { useState } from 'react';
import { 
  RefreshCw, 
  Edit3, 
  Check, 
  Send, 
  Copy, 
  CheckCircle2, 
  Bot
} from 'lucide-react';

export default function SuggestedReplyPanel({ 
  email, 
  onSendReply,
  onNotify
}) {
  const replies = email?.suggestedReplies || [];
  const [currentReplyIndex, setCurrentReplyIndex] = useState(0);
  const [isEditing, setIsEditing] = useState(false);
  const [editedText, setEditedText] = useState(replies[0]?.text || '');
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!email || replies.length === 0) {
    return (
      <div className="bg-white rounded-xl border border-slate-200 p-5 text-center text-slate-400">
        <Bot className="w-8 h-8 mx-auto text-slate-300 mb-2" />
        <p className="text-xs">No suggested reply available for this message.</p>
      </div>
    );
  }

  const currentReply = replies[currentReplyIndex] || replies[0];

  // Regenerate reply (cycles through available mock replies with a brief loading effect)
  const handleRegenerate = () => {
    setIsRegenerating(true);
    setTimeout(() => {
      const nextIndex = (currentReplyIndex + 1) % replies.length;
      setCurrentReplyIndex(nextIndex);
      setEditedText(replies[nextIndex].text);
      setIsRegenerating(false);
      setIsEditing(false);
      onNotify?.('AI generated a new response draft');
    }, 450);
  };

  // Toggle edit state
  const handleToggleEdit = () => {
    if (isEditing) {
      setIsEditing(false);
      onNotify?.('Reply draft updated');
    } else {
      setIsEditing(true);
    }
  };

  // Copy reply to clipboard
  const handleCopy = () => {
    navigator.clipboard?.writeText(editedText);
    setCopied(true);
    onNotify?.('Reply copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  // Send mock reply
  const handleSend = () => {
    onSendReply?.({
      emailId: email.id,
      text: editedText,
      tone: currentReply.tone
    });
    onNotify?.('Reply sent successfully!');
  };

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
      
      {/* Header */}
      <div className="p-4 bg-gradient-to-r from-purple-50 via-indigo-50/50 to-white border-b border-slate-200/80 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-purple-600 flex items-center justify-center text-white shadow-xs">
            <Bot className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-slate-900 tracking-tight">Suggested Reply</h3>
            <p className="text-[10px] text-slate-500">Contextual draft generated by AI</p>
          </div>
        </div>

        {/* Tone indicator */}
        <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 border border-purple-200">
          Tone: {currentReply.tone}
        </span>
      </div>

      {/* Reply Body / Textarea */}
      <div className="p-4 space-y-3">
        {isRegenerating ? (
          <div className="h-44 flex flex-col items-center justify-center space-y-2 bg-slate-50 rounded-lg border border-dashed border-slate-200">
            <RefreshCw className="w-5 h-5 text-indigo-600 animate-spin" />
            <p className="text-xs font-medium text-slate-500">Drafting alternate AI response...</p>
          </div>
        ) : isEditing ? (
          <div className="space-y-1.5">
            <div className="flex items-center justify-between text-[11px] text-slate-400">
              <span>Editing draft response:</span>
              <span className="text-indigo-600 font-medium">Auto-saving</span>
            </div>
            <textarea
              rows={7}
              value={editedText}
              onChange={(e) => setEditedText(e.target.value)}
              className="w-full p-3 text-xs leading-relaxed text-slate-800 bg-slate-50/80 border border-indigo-300 rounded-lg focus:outline-hidden focus:ring-2 focus:ring-indigo-500/20 focus:bg-white resize-y font-sans"
              placeholder="Type or edit your reply..."
            />
          </div>
        ) : (
          <div className="p-3.5 rounded-lg bg-slate-50/80 border border-slate-200/80 text-xs text-slate-800 leading-relaxed whitespace-pre-line max-h-56 overflow-y-auto">
            {editedText}
          </div>
        )}

        {/* Control Buttons */}
        <div className="flex items-center justify-between gap-2 pt-1">
          
          <div className="flex items-center gap-1.5">
            {/* Regenerate Button */}
            <button
              onClick={handleRegenerate}
              disabled={isRegenerating}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-100 border border-slate-200 transition-colors disabled:opacity-50"
              title="Regenerate alternate response"
            >
              <RefreshCw className={`w-3.5 h-3.5 text-slate-500 ${isRegenerating ? 'animate-spin' : ''}`} />
              <span>Regenerate</span>
            </button>

            {/* Edit / Save Button */}
            <button
              onClick={handleToggleEdit}
              className={`
                inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border
                ${isEditing 
                  ? 'bg-indigo-50 text-indigo-700 border-indigo-300' 
                  : 'text-slate-700 hover:bg-slate-100 border-slate-200'}
              `}
              title={isEditing ? 'Save edits' : 'Edit response text'}
            >
              {isEditing ? (
                <>
                  <Check className="w-3.5 h-3.5 text-indigo-600" />
                  <span>Done</span>
                </>
              ) : (
                <>
                  <Edit3 className="w-3.5 h-3.5 text-slate-500" />
                  <span>Edit</span>
                </>
              )}
            </button>
          </div>

          <div className="flex items-center gap-1.5">
            {/* Copy Button */}
            <button
              onClick={handleCopy}
              className="p-1.5 rounded-lg text-slate-500 hover:text-slate-700 hover:bg-slate-100 border border-slate-200 transition-colors"
              title="Copy to clipboard"
            >
              {copied ? <CheckCircle2 className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            </button>

            {/* Send Reply Button */}
            <button
              onClick={handleSend}
              className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-lg text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white shadow-xs transition-colors"
            >
              <Send className="w-3.5 h-3.5" />
              <span>Send Reply</span>
            </button>
          </div>

        </div>

      </div>

    </div>
  );
}
